### ISSUE TITLE
trouble with talador

### ISSUE THREAD

**Issue by deathmessinger** [Jiyambi/WoW-Pro-Guides#415] opened 2015-03-04 22:21 UTC
every time i go to load the guide for talador on my horde toon my game freezes :( it is only with this one guide the rest load just fine

**Comment by Ludovicus** [comment] 2015-03-07 14:14
OK.  I need a bit more information.
# PC or Mac?
# What version of the addon are you using?
# What other addons do you have?
# When you say "freeze" please be more precise.   Does the game instantly die?  Do you get the funny cursor after awhile?  Do you still get sounds?  Does the game eventually exit or crash?
# Can you load the guide on another Horde toon, even if under-level?
# Can you try turning on debugging on the addon and seeing what is the last thing printed to the console?

FWIW, I loaded Talador on my own horde toon loads fine.

**Comment by Threep** [comment] 2015-03-07 15:14
Same problem. Something loops infinitely.

PC, occurs with 6.1.1 and 6.1.0 but not with previous versions, freezes immediately after "initializing guide" with debug on and doesn't return, confirmed with no other addons than WoW-Pro and TomTom and on two different characters.

Reverted to a previous version of just that guide when it happened and did half the zone, still freezes when I switch to the latest.

**Comment by Ludovicus** [comment] 2015-03-07 16:00
Oh, pooh.  Since it happens with 6.1.0, I can't blame the ACE addons.

Sounds like we must be tickling a Blizzard Client PC problem.

I'll see if I can reproduce it on my PC laptop.


But first,  I have to chop ice around an outlet and a water spigot so the "Ice Dam Man" can steam them away on my house.

**Comment by Ludovicus** [comment] 2015-03-07 16:27
The guide hangs on my PC laptop, but not my Mac Desktop using a stock 6.1.1 and a copy of my config files from my Mac.

It has to be a Blizzard problem, but we must be tickling it.
Sigh.  Let me investigate some more.

**Comment by Ludovicus** [comment] 2015-03-07 23:19
The problem occurs when when we call the AceEvent:SendMessage() function.  It returns, but then the machinery goes off the deep end.  I will see if I can reduce it to a test case that I can submit as a ticket.

**Comment by Threep** [comment] 2015-03-07 23:32
Tested every 85+ guide, Talador is the only one that does it. So I guess really weird is it.

**Comment by Ludovicus** [comment] 2015-03-08 00:23
Hmm. In terms of size, 95_96_Emmaleah_Talador.lua is smaller than 92_94_Emmaleah_Gorgrond.lua or 92_94_Emmaleah_Gorgrond.lua, so that cant be it.  But Talador is one of the largest, so I can't discount memory manager issues.

Now going to put debug messages in the ACE3 code.

**Comment by Ludovicus** [comment] 2015-03-08 00:55
BTW, Do you also get a hang loading the Neutral Netherstorm guide?

**Comment by Threep** [comment] 2015-03-08 01:19
Every other levelling guide loads without a freeze. Also confirmed it happens on a fresh level 1 with no other addons loaded.

**Comment by Ludovicus** [comment] 2015-03-08 01:59
I have reports of non-WoW-Pro users with similar symptoms.  I am hoping that we can find another addon with the same problem and find that it uses  a suspicious ACE library in common.

**Comment by Threep** [comment] 2015-03-08 03:25
The freeze is caused by the error in line 452

**Comment by Ludovicus** [comment] 2015-03-08 12:45
Hmm, interesting.   That would imply that on Windows, the LUA engine is running asynchronously from the logging input.  Worse yet, that line should have been flagged by the new parser.

**Comment by Ludovicus** [comment] 2015-03-08 14:49
Threep, edit the file and make that line look like:
```
l Treasure of Ango'rosh|QID|34257|
``` 
That is a lowercase L at the start.    I can now make the Mac client also fail at the same point, but it only happens 1 out of 5 tries.  Looks like memory corruption.

**Comment by Ludovicus** [comment] 2015-03-08 22:12
This should now be fixed in the GitHub version.

**Closed by Ludovicus** 2015-03-08 22:12 UTC
Labels: Bug
