### ISSUE TITLE
Arrow in ocean

### ISSUE THREAD

**Issue by Gennefur** [Jiyambi/WoW-Pro-Guides#393] opened 2015-01-03 00:53 UTC
Sorry if this isn't the place for this.  I can't get into the main site page, won't send emails for people to sign up, and we are posting on curse.com but I don't know if anyone is looking there.  Once TomTom updated and Carbonite Wowpro make the arrows go into the ocean and zoom out really far.  Some people had theories that WoWpro coding was off of an older version or TomTom, I don't know.  If I take off WoWPro I don't have this issue with the arrow going into the ocean for where to go on my quest.  I was looking on the web page to see if you guys are aware or working on something but I haven't seen an updated post since 12/19 and Carbonite and Tomtom updated after that.  I love your addon and want to use it.  So if someone gets a chance to check out the comments on curse we would all appreciate it or sets up the website so we can pester you there directly.  I put in a pict someone had posted to show how the arrow is all crazy for us.  Thanks!
![crazyoceanarrow](https://cloud.githubusercontent.com/assets/10376901/5601046/bdce0a56-929f-11e4-9e11-8b2c09a594f7.jpg)

**Comment by Ludovicus** [comment] 2015-01-03 15:43
Actually, this is the **best** place to post bugs, since I get emails each time something changes here.

Anyways, so I need to know what versions of WoW-Pro and TomTom/Carbonite you are using and what guide you are using.

**Comment by Gennefur** [comment] 2015-01-03 21:11
Oh good!  I felt like I was kind of stalking you trying to find a place to post to you because I love your addon that much.  I was using Carbonite 6.0-1(new one they updated and broke into different sections you can download and I put them all on), Tomtom  v60000-1.1.1, and WoWPro 6.0.3G.  Everything was fine until updates with Tomtom and Carbonite on 12/21 and then my arrow went on strike.  If I take off WoWPro then the arrow doesn't run away.  Thanks!

**Comment by Ludovicus** [comment] 2015-01-04 13:54
Oh,  Version G had definite problems with mapping,  
Please update to version H and you should be OK.

**Comment by Gennefur** [comment] 2015-01-04 20:31
Ohhhhh I said that wrong for the WoWPro version.  I meant to post I had 6.0.3H not 6.0.3G.  I was switching up versions so much trying to figure out what was making the map problems for me I think I confused myself.  But I am 100% sure of it being H and not G.  I just tried putting H on and my map zoomed out and went off into the ocean again.  What I ended up doing was rolling back to G and it works but doesn't have all the updates on it.  Kinda weird that is G had problems with mapping it works better for me then H with Carbonite and TomTom.

**Comment by Ludovicus** [comment] 2015-01-04 21:27
OK.  Go to the addon control panel.   Turn on Debugging.  Clear the log.  Right click on the top of the "guide" window and then select "Reset this guide".  click on the control panel "Show the log" button.  A window will open up.  Cut/paste the log here.

What I want to know is where is the addon setting the TomTom arrow to (coordinates/zone) and where is it showing up.

**Comment by Gennefur** [comment] 2015-01-05 07:22
Sorry it took so long to get back, my internet went down for awhile.  Well now that I got you and I am trying to replicate it I am having no issues.  Carbonite had an update through curse for the maps and I also updated WoWPro so now I don't have any problems.  Yay!  So I don't know if it was a conflict with their mod and it got patched or what.  But it is all working great now.  Thank you for being patient with me and thank you for your amazing mod.  :D

**Comment by Gennefur** [comment] 2015-01-05 15:49
Ok I got the bug again.  I don't know what it is doing it since I am now on the latest versions of everything.  I went in and got the log like you said.  The only difference I had between the two charas, the one where the map wasn't off into the ocean and this one where it is, is that the first one was over half done with the zone and this toon is just starting out.  I don't know if that makes a difference or not.  

074549.0000 ~ WoWPro: Log Reset from UI, WoWPro Version 6.0.3J.
074703.0001 ~ WoWPro: Signaled for LoadGuide nil
074704.0002 ~ WoWPro: WoWPro_LoadGuide: starting guide cleanup:  ShadowDraenor
074704.0003 ~ WoWPro: Loading Guide: ShadowDraenor
074704.0004 ~ WoWPro: Initializing Guide ShadowDraenor.
074704.0005 ~ WoWPro: Signaled for LoadGuideSteps for ShadowDraenor
074704.0006 ~ WoWPro: LoadGuideSteps(ShadowDraenor)
074704.0007 ~ WoWPro: Parsing Guide, 687 steps
074704.0008 ~ WoWPro: Guide Parsed. 516 steps stored.
074704.0009 ~ WoWPro_Leveling: Recorded load for guide ShadowDraenor at 1420472824
074704.0010 ~ WoWPro: Signaled for GuideSetup for ShadowDraenor
074704.0011 ~ WoWPro: SetupGuideReal(ShadowDraenor): Type: Leveling, recordQIDs:
074704.0012 ~ WoWPro: WoWPro:PopulateQuestLog()
074704.0013 ~ WoWPro: PopulateQuestLog: Entries 31, Quests 20.
074704.0014 ~ WoWPro: PopulateQuestLog: Header Cooking  @ 1
074704.0015 ~ WoWPro: PopulateQuestLog: Quest 33020 [The Lost Secret of the Secret Ingredient] @ 2
074704.0016 ~ WoWPro: PopulateQuestLog: Header Darkmoon Faire  @ 3
074704.0017 ~ WoWPro: PopulateQuestLog: Quest 29433 [Test Your Strength] @ 4
074704.0018 ~ WoWPro: PopulateQuestLog: Header Isle of Thunder  @ 5
074704.0019 ~ WoWPro: PopulateQuestLog: Quest 32707 [Secrets in the Isle of Thunder] @ 6
074704.0020 ~ WoWPro: PopulateQuestLog: Header Krasarang Wilds  @ 7
074704.0021 ~ WoWPro: PopulateQuestLog: Quest 29874 [Kang Bramblestaff] @ 8
074704.0022 ~ WoWPro: PopulateQuestLog: Quest 29873 [Ken-Ken] @ 9
074704.0023 ~ WoWPro: PopulateQuestLog: Header Kun-Lai Summit  @ 10
074704.0024 ~ WoWPro: PopulateQuestLog: Quest 31455 [The Shado-Pan] @ 11
074704.0025 ~ WoWPro: PopulateQuestLog: Quest 30944 [It Takes A Village] @ 12
074704.0026 ~ WoWPro: PopulateQuestLog: Quest 30592 [The Burlap Trail: To Burlap Waystation] @ 13
074704.0027 ~ WoWPro: PopulateQuestLog: Header Pandaren Campaign  @ 14
074704.0028 ~ WoWPro: PopulateQuestLog: Quest 32246 [Meet the Scout] @ 15
074704.0029 ~ WoWPro: PopulateQuestLog: Header Shadowmoon Valley  @ 16
074704.0030 ~ WoWPro: PopulateQuestLog: Quest 33072 [Into Twilight] @ 17
074704.0031 ~ WoWPro: PopulateQuestLog: Quest 34778 [Migrant Workers] @ 18
074704.0032 ~ WoWPro: PopulateQuestLog: Quest 35444 [The Southern Wilds] @ 19
074704.0033 ~ WoWPro: PopulateQuestLog: Header The Jade Forest  @ 20
074704.0034 ~ WoWPro: PopulateQuestLog: Quest 29904 [Bigger Fish to Fry] @ 21
074704.0035 ~ WoWPro: PopulateQuestLog: Quest 29888 [Seek Out the Lorewalker] @ 22
074704.0036 ~ WoWPro: PopulateQuestLog: Header Timeless Isle  @ 23
074704.0037 ~ WoWPro: PopulateQuestLog: Quest 33338 [Empowering the Hourglass] @ 24
074704.0038 ~ WoWPro: PopulateQuestLog: Quest 33374 [Path of the Mistwalker] @ 25
074704.0039 ~ WoWPro: PopulateQuestLog: Quest 33334 [Strong Enough To Survive] @ 26
074704.0040 ~ WoWPro: PopulateQuestLog: Header Townlong Steppes  @ 27
074704.0041 ~ WoWPro: PopulateQuestLog: Quest 30895 [Improvised Ammunition] @ 28
074704.0042 ~ WoWPro: PopulateQuestLog: Header Valley of the Four Winds  @ 29
074704.0043 ~ WoWPro: PopulateQuestLog: Quest 30048 [Li Li and the Grain] @ 30
074704.0044 ~ WoWPro: PopulateQuestLog: Quest 29872 [Lin Tenderpaw] @ 31
074704.0045 ~ WoWPro: Quest Log populated. 20 quests found.
074704.0046 ~ WoWPro: Running: AutoCompleteQuestUpdate(questComplete=nil)
074704.0047 ~ WoWPro: Signaled for UpdateGuide from WoWPro:LoadGuideSteps()
074705.0048 ~ WoWPro: UpdateGuideReal(): Running
074705.0049 ~ WoWPro: Running: UpdateGuideReal(), WoWPro Version 6.0.3J.
074705.0050 ~ WoWPro: Called WoWPro.NextStep(1,1)
074705.0051 ~ WoWPro: Prof permaskip qid 35342 for no Alchemy
074705.0052 ~ WoWPro: Prof permaskip qid 36308 for no Enchanting
074705.0053 ~ WoWPro: Prof permaskip qid 36286 for no Engineering
074705.0054 ~ WoWPro: Prof permaskip qid 36239 for no Inscription
074705.0055 ~ WoWPro: Prof permaskip qid 36408 for no Jewelcrafting
074705.0056 ~ WoWPro: Prof permaskip qid 36236 for no Tailoring
074705.0057 ~ WoWPro: SkippedQUID(100, qid=35342, T [The Mysterious Flask])
074705.0058 ~ WoWPro: SkippedQUID(102, qid=36236, T [The Cryptic Tome of Tailoring])
074705.0059 ~ WoWPro: SkippedQUID(104, qid=36308, T [Enchanted Highmaul Bracer])
074705.0060 ~ WoWPro: Step T [The Young Alchemist/35343] skipped as not in QuestLog
074705.0061 ~ WoWPro: Step T [The Missing Father/35344] skipped as not in QuestLog
074705.0062 ~ WoWPro: Step C [Shocking Assistance/35345] skipped as not in QuestLog
074705.0063 ~ WoWPro: Step T [Shocking Assistance/35345] skipped as not in QuestLog
074705.0064 ~ WoWPro: Step T [A Call for Huntsman/36176] skipped as not in QuestLog
074705.0065 ~ WoWPro: Step C [Friendly Competition/36177] skipped as not in QuestLog
074705.0066 ~ WoWPro: Step C [Friendly Competition/36177] skipped as not in QuestLog
074705.0067 ~ WoWPro: Step C [Friendly Competition/36177] skipped as not in QuestLog
074705.0068 ~ WoWPro: Step T [Friendly Competition/36177] skipped as not in QuestLog
074705.0069 ~ WoWPro: Step T [Fair Trade/36185] skipped as not in QuestLog
074705.0070 ~ WoWPro: SkippedQUID(121, qid=36408, T [A Power Lost])
074705.0071 ~ WoWPro: Step C [Restoration/36409] skipped as not in QuestLog
074705.0072 ~ WoWPro: Step T [Restoration/36409] skipped as not in QuestLog
074705.0073 ~ WoWPro: Running: WoWPro:RowUpdate()
074705.0074 ~ WoWPro: Called WoWPro.NextStep(129,1)
074705.0075 ~ WoWPro: Called WoWPro.NextStep(130,2)
074705.0076 ~ WoWPro: Step C [Circle the Wagon/34779] skipped as not in QuestLog
074705.0077 ~ WoWPro: Step C [Circle the Wagon/34779] skipped as not in QuestLog
074705.0078 ~ WoWPro: Step C [Circle the Wagon/34779] skipped as not in QuestLog
074705.0079 ~ WoWPro: Step T [Circle the Wagon/34779] skipped as not in QuestLog
074705.0080 ~ WoWPro: Step C [Primary Pilon/34780] skipped as not in QuestLog
074705.0081 ~ WoWPro: Step C [Secondary Pylon/34780] skipped as not in QuestLog
074705.0082 ~ WoWPro: Step C [Tertiary Pylon/34780] skipped as not in QuestLog
074705.0083 ~ WoWPro: Step T [Invisible Ramparts/34780] skipped as not in QuestLog
074705.0084 ~ WoWPro: Step C [Defenstrations/34781] skipped as not in QuestLog
074705.0085 ~ WoWPro: Step T [Defenstrations/34781] skipped as not in QuestLog
074705.0086 ~ WoWPro: Step T [Ameeka, Master Tailor/36262] skipped as not in QuestLog
074705.0087 ~ WoWPro: Step T [The Exarch Council/34782] skipped as not in QuestLog
074705.0088 ~ WoWPro: Step T [Naielle, The Rangari/34783] skipped as not in QuestLog
074705.0089 ~ WoWPro: SkippedQUID(153, qid=36239, T [A Mysterious Satchel])
074705.0090 ~ WoWPro: Step C [Slow and Steady/36240] skipped as not in QuestLog
074705.0091 ~ WoWPro: Step C [The Sting/34790] skipped as not in QuestLog
074705.0092 ~ WoWPro: Step C [Fun with Fungus/34784] skipped as not in QuestLog
074705.0093 ~ WoWPro: Step C [The Sting/34790] skipped as not in QuestLog
074705.0094 ~ WoWPro: Step C [Slow and Steady/36240] skipped as not in QuestLog
074705.0095 ~ WoWPro: Step T [Slow and Steady/36240] skipped as not in QuestLog
074705.0096 ~ WoWPro: Step T [The Power of Preservation/36241] skipped as not in QuestLog
074705.0097 ~ WoWPro: Step T [The Sting/34790] skipped as not in QuestLog
074705.0098 ~ WoWPro: Step T [Fun with Fungus/34784] skipped as not in QuestLog
074705.0099 ~ WoWPro: Step T [Hataaru, the Artificer/34785] skipped as not in QuestLog
074705.0100 ~ WoWPro: Step C [Engorged Goren/34786] skipped as not in QuestLog
074705.0101 ~ WoWPro: Step C [Shut 'er Down/35070] skipped as not in QuestLog
074705.0102 ~ WoWPro: Step C [Engorged Goren/34786] skipped as not in QuestLog
074705.0103 ~ WoWPro: Step T [Engorged Goren/34786] skipped as not in QuestLog
074705.0104 ~ WoWPro: Step T [Shut 'er Down/35070] skipped as not in QuestLog
074705.0105 ~ WoWPro: Step T [Exarch Maladaar/34787] skipped as not in QuestLog
074705.0106 ~ WoWPro: Step C [Trust No One/35552] skipped as not in QuestLog
074705.0107 ~ WoWPro: Step T [Trust No One/35552] skipped as not in QuestLog
074705.0108 ~ WoWPro: Step T [Warning the Exarchs/34791] skipped as not in QuestLog
074705.0109 ~ WoWPro: Step C [Speaker for the Dead/34789] skipped as not in QuestLog
074705.0110 ~ WoWPro: Step C [Speaker for the Dead/34789] skipped as not in QuestLog
074705.0111 ~ WoWPro: Step T [Speaker for the Dead/34789] skipped as not in QuestLog
074705.0112 ~ WoWPro: Step C [The Traitor's True Name/34792] skipped as not in QuestLog
074705.0113 ~ WoWPro: Step C [The Traitor's True Name/34792] skipped as not in QuestLog
074705.0114 ~ WoWPro: Step C [The Traitor's True Name/34792] skipped as not in QuestLog
074705.0115 ~ WoWPro: Step T [The Traitor's True Name/34792] skipped as not in QuestLog
074705.0116 ~ WoWPro: Step C [Friend of the Exarchs/34788] skipped as not in QuestLog
074705.0117 ~ WoWPro: Step T [Friend of the Exarchs/34788] skipped as not in QuestLog
074705.0118 ~ WoWPro: Called WoWPro.NextStep(195,3)
074705.0119 ~ WoWPro: SkippedQUID(195, qid=36286, T [Gnomish Location Transponder])
074705.0120 ~ WoWPro: Step C [Snatch 'n' Grab/36287] skipped as not in QuestLog
074705.0121 ~ WoWPro: Step T [Snatch 'n' Grab/36287] skipped as not in QuestLog
074705.0122 ~ WoWPro: Called WoWPro.NextStep(200,4)
074705.0123 ~ WoWPro: Step C [The Big Haul/33084] skipped as not in QuestLog
074705.0124 ~ WoWPro: Step T [The Big Haul/33084] skipped as not in QuestLog
074705.0125 ~ WoWPro: Step f [Path of the Light] ACTIVE 35444, skip=false
074705.0126 ~ WoWPro: Called WoWPro.NextStep(204,5)
074705.0127 ~ WoWPro: Step R [The Draakorium] ACTIVE 35444, skip=false
074705.0128 ~ WoWPro: Called WoWPro.NextStep(205,6)
074705.0129 ~ WoWPro: Step T [The Southern Wilds] ACTIVE 35444, skip=false
074705.0130 ~ WoWPro: Called WoWPro.NextStep(206,7)
074705.0131 ~ WoWPro: Called WoWPro.NextStep(207,8)
074705.0132 ~ WoWPro: Step T [The Southern Wilds/35459] skipped as not in QuestLog
074705.0133 ~ WoWPro: Step T [The Southern Wilds/35450] skipped as not in QuestLog
074705.0134 ~ WoWPro: Called WoWPro.NextStep(211,9)
074705.0135 ~ WoWPro: Called WoWPro.NextStep(213,10)
074705.0136 ~ WoWPro: Step C [Crippled Caravan/33786] skipped as not in QuestLog
074705.0137 ~ WoWPro: Step T [Crippled Caravan/33786] skipped as not in QuestLog
074705.0138 ~ WoWPro: Called WoWPro.NextStep(216,11)
074705.0139 ~ WoWPro: Called WoWPro.NextStep(217,12)
074705.0140 ~ WoWPro: Step C [Wanted: Maa'run's Hoof/33836] skipped as not in QuestLog
074705.0141 ~ WoWPro: Step C [Swamplighter Queen/33808] skipped as not in QuestLog
074705.0142 ~ WoWPro: Step C [Moonlit Herb/33787] skipped as not in QuestLog
074705.0143 ~ WoWPro: Step C [Riot Blossom/33787] skipped as not in QuestLog
074705.0144 ~ WoWPro: Step C [Swamplighter Drones/33787] skipped as not in QuestLog
074705.0145 ~ WoWPro: Step C [Twilight Riverbeast/33787] skipped as not in QuestLog
074705.0146 ~ WoWPro: Step C [Moonlit Herb/33787] skipped as not in QuestLog
074705.0147 ~ WoWPro: Step C [Twilight Riverbeast/33787] skipped as not in QuestLog
074705.0148 ~ WoWPro: Step C [Swamplighter Drones/33787] skipped as not in QuestLog
074705.0149 ~ WoWPro: Step C [Riot Blossom/33787] skipped as not in QuestLog
074705.0150 ~ WoWPro: Step T [Fiona's Solution/33787] skipped as not in QuestLog
074705.0151 ~ WoWPro: Step T [Swamplighter Queen/33808] skipped as not in QuestLog
074705.0152 ~ WoWPro: Step C [Cooking With Unstable Herbs/33788] skipped as not in QuestLog
074705.0153 ~ WoWPro: Step C [Cooking With Unstable Herbs/33788] skipped as not in QuestLog
074705.0154 ~ WoWPro: Step C [Cooking With Unstable Herbs/33788] skipped as not in QuestLog
074705.0155 ~ WoWPro: Step T [Cooking With Unstable Herbs/33788] skipped as not in QuestLog
074705.0156 ~ WoWPro: Called WoWPro.NextStep(239,13)
074705.0157 ~ WoWPro: Step C [Botani Beatdown/34995] skipped as not in QuestLog
074705.0158 ~ WoWPro: Step C [Rotting Riverbeasts/34996] skipped as not in QuestLog
074705.0159 ~ WoWPro: Called WoWPro.NextStep(242,14)
074705.0160 ~ WoWPro: Step C [Slumberbloom/34997] skipped as not in QuestLog
074705.0161 ~ WoWPro: Step C [Forever Young/34994] skipped as not in QuestLog
074705.0162 ~ WoWPro: Step C [Poison Paralysis/35006] skipped as not in QuestLog
074705.0163 ~ WoWPro: Step C [Blademoon Bloom/35014] skipped as not in QuestLog
074705.0164 ~ WoWPro: Step T [Blademoon Bloom/35014] skipped as not in QuestLog
074705.0165 ~ WoWPro: Step C [Gestating Genesaur/35015] skipped as not in QuestLog
074705.0166 ~ WoWPro: Step T [Gestating Genesaur/35015] skipped as not in QuestLog
074705.0167 ~ WoWPro: Step C [Poison Paralysis/35006] skipped as not in QuestLog
074705.0168 ~ WoWPro: Step C [Poison Paralysis/35006] skipped as not in QuestLog
074705.0169 ~ WoWPro: Step C [Slumberbloom/34997] skipped as not in QuestLog
074705.0170 ~ WoWPro: Step T [Slumberbloom/34997] skipped as not in QuestLog
074705.0171 ~ WoWPro: Step C [Forever Young/34994] skipped as not in QuestLog
074705.0172 ~ WoWPro: Step C [Botani Beatdown/34995] skipped as not in QuestLog
074705.0173 ~ WoWPro: Step T [Rotting Riverbeasts/34996] skipped as not in QuestLog
074705.0174 ~ WoWPro: Step T [Forever Young/34994] skipped as not in QuestLog
074705.0175 ~ WoWPro: Step T [Botani Beatdown/34995] skipped as not in QuestLog
074705.0176 ~ WoWPro: Step T [Poison Paralysis/35006] skipped as not in QuestLog
074705.0177 ~ WoWPro: Step T [Fiona/35617] skipped as not in QuestLog
074705.0178 ~ WoWPro: Step T [Wanted: Maa'run's Hoof/33836] skipped as not in QuestLog
074705.0179 ~ WoWPro: Step R [Twilight Glade] ACTIVE 33072, skip=false
074705.0180 ~ WoWPro: Called WoWPro.NextStep(264,15)
074705.0181 ~ WoWPro: Running WoWPro:UpdateQuestTracker()
074705.0182 ~ WoWPro: profile.track=true action=T questtext=nil lootitem=nil
074705.0183 ~ WoWPro: UQT: Track Text for T [Migrant Workers] to ''
074705.0184 ~ WoWPro: profile.track=true action=f questtext=nil lootitem=nil
074705.0185 ~ WoWPro: UQT: Track Text for f [Fey Landing] to ''
074705.0186 ~ WoWPro: profile.track=true action=A questtext=nil lootitem=nil
074705.0187 ~ WoWPro: UQT: Track Text for A [The Big Haul] to ''
074705.0188 ~ WoWPro: profile.track=true action=f questtext=nil lootitem=nil
074705.0189 ~ WoWPro: UQT: Track Text for f [Path of the Light] to ''
074705.0190 ~ WoWPro: profile.track=true action=R questtext=nil lootitem=nil
074705.0191 ~ WoWPro: UQT: Track Text for R [The Draakorium] to ''
074705.0192 ~ WoWPro: profile.track=true action=T questtext=nil lootitem=nil
074705.0193 ~ WoWPro: UQT: Track Text for T [The Southern Wilds] to ''
074705.0194 ~ WoWPro: profile.track=true action=A questtext=nil lootitem=nil
074705.0195 ~ WoWPro: UQT: Track Text for A [The Southern Wilds] to ''
074705.0196 ~ WoWPro: profile.track=true action=A questtext=nil lootitem=nil
074705.0197 ~ WoWPro: UQT: Track Text for A [Crippled Caravan] to ''
074705.0198 ~ WoWPro: profile.track=true action=f questtext=nil lootitem=nil
074705.0199 ~ WoWPro: UQT: Track Text for f [The Draakorium] to ''
074705.0200 ~ WoWPro: profile.track=true action=A questtext=nil lootitem=nil
074705.0201 ~ WoWPro: UQT: Track Text for A [Fiona's Solution] to ''
074705.0202 ~ WoWPro: profile.track=true action=A questtext=nil lootitem=nil
074705.0203 ~ WoWPro: UQT: Track Text for A [Swamplighter Queen] to ''
074705.0204 ~ WoWPro: profile.track=true action=A questtext=nil lootitem=nil
074705.0205 ~ WoWPro: UQT: Track Text for A [Rotting Riverbeasts] to ''
074705.0206 ~ WoWPro: profile.track=true action=A questtext=nil lootitem=nil
074705.0207 ~ WoWPro: UQT: Track Text for A [Slumberbloom] to ''
074705.0208 ~ WoWPro: profile.track=true action=R questtext=nil lootitem=nil
074705.0209 ~ WoWPro: UQT: Track Text for R [Twilight Glade] to ''
074705.0210 ~ WoWPro: profile.track=true action=f questtext=nil lootitem=nil
074705.0211 ~ WoWPro: UQT: Track Text for f [Twilight Glade] to ''
074705.0212 ~ WoWPro: Called WoWPro.NextStepNotSticky(129)
074705.0213 ~ WoWPro: Called WoWPro.NextStep(129,1)
074705.0214 ~ WoWPro: WoWPro.NextStepNotSticky=129: T [Migrant Workers] 
074705.0215 ~ WoWPro: MapPoint: LastMapPoint=129 [55.99,32.61@947/0] in Shadowmoon Valley@Draenor. No update needed.

**Comment by Ludovicus** [comment] 2015-03-21 17:22
Closing as no longer reproducible.

**Closed by Ludovicus** 2015-03-21 17:22 UTC
